# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{matrix.os}}
    env:
      CONFIGURATION: Release
    permissions:
      actions: write
      artifact-metadata: write
      checks: write
      contents: write 
      pull-requests: write      
    outputs:
      assemblySemVer: ${{ steps.setup.outputs.assemblySemVer }}
      GitVersion_FullSemVer: ${{ steps.setup.outputs.GitVersion_FullSemVer }}
      semVer: ${{ steps.setup.outputs.semVer }}
      
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive

    - shell: pwsh
      run: Get-ChildItem -Recurse | select FullName

    - id: setup
      uses: ./actions/steps/setup

    - id: build
      uses: ./actions/steps/dotnet/build

    - id: tag-commit
      uses: ./actions/steps/git/tag-commit
      with:
        version: ${{ steps.setup.outputs.GitVersion_FullSemVer }}

  unit-test:
    needs: build
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    permissions:
      contents: read
      issues: write

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive

    - uses: ./actions/steps/setup
    - uses: ./actions/steps/dotnet/test
      with:
        assembly-semver: ${{ needs.build.outputs.assemblySemVer }}
        gitversion-full-semver: ${{ needs.build.outputs.GitVersion_FullSemVer }}

  benchmark:
    needs: build
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    permissions:
      contents: read
      issues: write
      actions: read

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive

    - uses: ./actions/steps/setup
    # - uses: ./actions/steps/benchmark
    #   with:
    #     configuration: ${{ env.CONFIGURATION }}
    #     project: <PATH>
    #     job: short
    #     exporters: GitHub
    #     filter: "*"

  lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive
        

    # - uses: ./actions/steps/dotnet/format
    - uses: ./actions/steps/rumdl

  codeql:
    env:
      CONFIGURATION: Release
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive

    - uses: ./actions/steps/codeql

  pr-size:
    if: github.event_name == 'pull_request'
    runs-on: windows-latest
    permissions:
      contents: read
      issues: read
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive

    - uses: ./actions/steps/pr-size

